[profile.ci]
fail-fast = false
retries = 1
slow-timeout = { period = "30s", terminate-after = 4 }

[profile.default]
fail-fast = true
retries = 0
slow-timeout = { period = "15s", terminate-after = 8 }