[[arena]]
name = "one"
workdir = "one-a"
datadir = "one-a/data"
disk_usage.max = "16M"
disk_usage.leave = "10%"

[[arena]]
name = "two"
workdir = "two-a"
datadir = "two-a/data"
disk_usage.max = "16M"
disk_usage.leave = "10%"

[[peer]]
name = "b"
address = "127.0.0.1:8001"
pubkey = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAZvriEx8hZEAildpfeifrv0Z5xED/kkK7wzT5Gel+w/w=
-----END PUBLIC KEY-----
"""

[cache]
db = "a.db"
