[[arena]]
name = "one"
workdir = "one-b"
datadir = "one-b/data"

[[arena]]
name = "two"
workdir = "two-b"
datadir = "two-b/data"

[[peer]]
name = "a"
address = "127.0.0.1:7001"
pubkey = """
-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAPjsIFMiDLwPSdJ90P6Dh+jbpk/EoeorE+2OsdTzxX+s=
-----END PUBLIC KEY-----
"""

[cache]
db = "b.db"
