name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'spec/**'
      - 'docs/**'
      - '.cursor/**'
      - '.vscode/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'spec/**'
      - 'docs/**'
      - '.cursor/**'
      - '.vscode/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  on-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: Install build dependencies
      run: "sudo apt-get install capnproto libcapnp-dev"
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@nextest
    - name: Build
      run: "cargo build"
    - name: Run tests
      run: "cargo nextest run --retries 1 --no-fail-fast"
    - name: Run doctests
      run: "cargo test --doc"

  on-macos:
    runs-on: macos-15
    steps:
    - name: Install build dependencies
      run: "brew install capnp"
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@nextest
    - name: Build
      run: "cargo build"
    - name: Run tests
      run: "cargo nextest run --retries 1 --no-fail-fast"
    - name: Run doctests
      run: "cargo test --doc"
