name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'spec/**'
      - 'docs/**'
      - '.cursor/**'
      - '.vscode/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'spec/**'
      - 'docs/**'
      - '.cursor/**'
      - '.vscode/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  on-linux:
    runs-on: ubuntu-24.04
    steps:
    - name: Install build dependencies
      run: "sudo apt-get install capnproto libcapnp-dev fuse3 libfuse3-dev"
    - name: Configure fuse
      run: "sudo sh -c \"echo user_allow_other >/etc/fuse.conf\""
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@nextest
    - name: Build
      run: "cargo build"
    - name: Run tests
      run: "RUST_LOG=realize_=debug cargo nextest run --retries 1 --no-fail-fast"
    - name: Run doctests
      run: "cargo test --doc"

  on-macos:
    runs-on: macos-15
    steps:
    - name: Install build dependencies
      run: "brew install capnp macfuse@dev fuse-t"
    - uses: actions/checkout@v4
    - uses: taiki-e/install-action@nextest
    - name: Build
      run: "cargo build"
    - name: Run tests
      run: "RUST_LOG=realize_=debug cargo nextest run --retries 1 --no-fail-fast --skip fuse"
    - name: Run doctests
      run: "cargo test --doc"
    - name: Run fuse tests
      run: "RUST_LOG=realize_=debug cargo nextest run fuse --no-capture"
